/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const c: typeof import('../../../../../src/style/theme$.css')['c']
  const createVar: typeof import('../../../../../src/style/theme$.css')['createVar']
  const recipe: typeof import('../../../../../src/style/theme$.css')['recipe']
  const s: typeof import('../../../../../src/style/theme$.css')['s']
  const style: typeof import('../../../../../src/style/theme$.css')['style']
  const transition: typeof import('../../../../../src/style/theme$.css')['transition']
  const transitionFn: typeof import('../../../../../src/style/theme$.css')['transitionFn']
}
